### ISSUE TITLE
error FSHARP: This expression was expected to have type     'Cmd<'a>'

### ISSUE THREAD

**Issue by kierepka** [fable-compiler/fable-templates#34] opened 2021-01-11 13:59 UTC
I'm trying to use Fulma and Fable 3.0 with .net5.0

I'm getting this error:

`
Compiling src\BioMindsSite.fsproj...
F# compilation finished in 6517ms
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Browser.4.0.0-alpha-2/navigation.fs(31,9): (31,56) error FSHARP: This expression was expected to have type
    'Cmd<'a>'
but here has type
    ''b list'     (code 1)
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Browser.4.0.0-alpha-2/navigation.fs(35,9): (38,30) error FSHARP: This expression was expected to have type
    'Cmd<'a>'
but here has type
    ''b list'     (code 1)
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Browser.4.0.0-alpha-2/navigation.fs(42,9): (42,32) error FSHARP: This expression was expected to have type
    'Cmd<'a>'
but here has type
    ''b list'     (code 1)
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Browser.4.0.0-alpha-2/navigation.fs(97,21): (97,41) error FSHARP: This expression was expected to have type
    'Cmd<Navigable<'c>>'
but here has type
    ''a list'     (code 1)
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Debugger.4.0.0-alpha-1/debugger.fs(97,13): (97,16) error FSHARP: The block following this 'let' is unfinished. Every code block is an expression and must have a result. 'let' cannot be the final code element in a block. Cons
ider giving this block an explicit result. (code 588)
Compilation failed
`

**Comment by MangelMaxime** [comment] 2021-01-11 16:18
@kierepka You seems to be using an alpha version of Elmish which is not recommended can you please try to use stable version instead? The latest stable version is version 3.x

**Comment by kierepka** [comment] 2021-01-11 17:00
```
E:/source/repos/BioMindsSite/src/.fable/Fable.Elmish.Browser.3.0.4/navigation.fs(110,54): (110,58) error FSHARP: The value or constructor 'subs' is not defined. Maybe you want one of the following:
   Sub
   subscribe (code 39)

```

3.0.3 is working

**Comment by MangelMaxime** [comment] 2021-01-12 11:09
Hum, 

I am using Fable.Elmish.Browser v 3.0.4 in my project without a problem:

Here is the extraction of my `paket.lock`

````fs
    Fable.Elmish (3.0.6)
      Fable.Core (>= 3.0)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.Browser (3.0.4)
      Fable.Browser.Dom (>= 1.0)
      Fable.Core (>= 3.0)
      Fable.Elmish (>= 3.0)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.Debugger (3.0.3)
      Fable.Core (>= 3.0)
      Fable.Elmish (>= 3.0)
      FSharp.Core (>= 4.6.2)
      Thoth.Json (>= 3.0)
    Fable.Elmish.HMR (4.0.1)
      Fable.Core (>= 3.0)
      Fable.Elmish.Browser (>= 3.0)
      Fable.Elmish.React (>= 3.0.1)
      FSharp.Core (>= 4.6.2)
    Fable.Elmish.React (3.0.1)
      Fable.Core (>= 3.0)
      Fable.Elmish (>= 3.0)
      Fable.React (>= 5.1)
      FSharp.Core (>= 4.6.2)
``` 

I think we will need a reproduction repository to help you further more because I see no reason why v3.0.4 would not work.

**Comment by MangelMaxime** [comment] 2021-03-05 13:50
I am closing this issue.

In theory, my answer is correct. Please feel free to re-open if needed.

**Closed by MangelMaxime** 2021-03-05 13:50 UTC
